### ISSUE TITLE
Welcome! Beginning a workflow.

### ISSUE THREAD

**Issue by blockheads** [blockheads/CSCI421DBMS#1]
So to everyone who is part of the group I think we should begin by creating a list of the available tasks, construct a project ( we can use the built in Github project ).

I also made a slack because Github doesn't really have a nice discussion forum, but again we don't have to use it.

[Slack](https://join.slack.com/t/csci421dbmsbestteam/shared_invite/enQtODk0NTY3MDQ3OTM3LWRjZGZhNzY2YWI2ODM5ZTU1NjgzZjZlZGFhYmI4NDY0M2ZiOWIzYWU1ZDJiODU4ZGE2YTJiMGI3M2FiMGEyOWY)

Anyways, I just want to get everyone's opinions right now I am thinking using the following

- Intelij
- Github
- Slack

Let me know what you think

**Comment by nseffernick** [comment]
Seems like the most obvious 3 resources to me.
